#!/usr/bin/env python3
"""Update testing-pyramid.d2 node colors based on pytest JUnit XML results.

Watches .test-results.xml (produced by pytest --junitxml) and updates the
D2 diagram to reflect test status per scenario:

  Red   (#ef9a9a)  — scenario has no corresponding test (not implemented)
  Green (#a5d6a7)  — test exists but is not passing
  Blue  (#90caf9)  — test is passing

Convention:
  - Each test *class* maps to a feature file:
      TestPsychometricFunction → psychometric-function.feature
  - Each test *method* maps to a scenario by normalized name:
      test_fit_a_psychometric_curve_per_block → "Fit a psychometric curve per block"

Usage:
  python tools/test-colorizer.py              # one-shot update
  python tools/test-colorizer.py --watch      # poll & update on change
"""

from __future__ import annotations

import re
import sys
import time
import xml.etree.ElementTree as ET
from pathlib import Path

# ---------------------------------------------------------------------------
# Color palette
# ---------------------------------------------------------------------------

RED = "#ef9a9a"  # Not implemented
GREEN = "#a5d6a7"  # Implemented but failing
BLUE = "#90caf9"  # Passing

MARKER = "# --- Test status colors (auto-generated by test-colorizer) ---"

TIER_TAG_RE = re.compile(r"@tier:(\w+)")
SCENARIO_RE = re.compile(r"\s+Scenario(?:\s+Outline)?:\s+(.+)")

TIER_VAR: dict[str, str] = {
    "e2e": "e2e_tier",
    "integration": "integration_tier",
    "domain": "domain_tier",
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def find_repo_root() -> Path:
    """Walk up from cwd until we find pyproject.toml."""
    d = Path.cwd()
    while True:
        if (d / "pyproject.toml").exists():
            return d
        parent = d.parent
        if parent == d:
            raise SystemExit("error: could not find repo root (pyproject.toml)")
        d = parent


def camel_to_kebab(name: str) -> str:
    """PascalCase → kebab-case  (PsychometricFunction → psychometric-function)."""
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1-\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1-\2", s).lower()


def normalize(text: str) -> str:
    """Lower-case, collapse non-alphanumeric to single space, strip."""
    return re.sub(r"[^a-z0-9]+", " ", text.lower()).strip()


def d2_id(stem: str) -> str:
    """Feature stem → D2 identifier (hyphens to underscores)."""
    return stem.replace("-", "_")


# ---------------------------------------------------------------------------
# Feature-file parsing
# ---------------------------------------------------------------------------


def parse_features(features_dir: Path) -> dict[str, list[str]]:
    """Return ``{feature_stem: [scenario_name, ...]}`` preserving order."""
    features: dict[str, list[str]] = {}
    for path in sorted(features_dir.glob("*.feature")):
        scenarios: list[str] = []
        for line in path.read_text().splitlines():
            m = SCENARIO_RE.match(line)
            if m:
                scenarios.append(m.group(1).strip())
        if scenarios:
            features[path.stem] = scenarios
    return features


def get_feature_tier(features_dir: Path, stem: str) -> str | None:
    """Read the ``@tier:`` tag from a .feature file → tier variable name."""
    path = features_dir / f"{stem}.feature"
    if not path.exists():
        return None
    for line in path.read_text().splitlines():
        m = TIER_TAG_RE.match(line)
        if m:
            return TIER_VAR.get(m.group(1))
    return None


# ---------------------------------------------------------------------------
# JUnit XML parsing
# ---------------------------------------------------------------------------


def parse_junit_xml(xml_path: Path) -> dict[str, dict[str, str]]:
    """Parse pytest JUnit XML → ``{feature_stem: {normalized_name: status}}``.

    Status is one of ``"passed"``, ``"failed"``, ``"skipped"``.
    """
    results: dict[str, dict[str, str]] = {}
    if not xml_path.exists():
        return results
    try:
        tree = ET.parse(xml_path)
    except ET.ParseError:
        return results

    for tc in tree.getroot().iter("testcase"):
        classname = tc.get("classname", "")
        name = tc.get("name", "")

        # Extract short class name (last dotted component)
        cls = classname.rsplit(".", 1)[-1]
        if not cls.startswith("Test"):
            continue

        feature_stem = camel_to_kebab(cls[4:])  # strip "Test" prefix

        # Determine status
        if tc.find("failure") is not None or tc.find("error") is not None:
            status = "failed"
        elif tc.find("skipped") is not None:
            status = "skipped"
        else:
            status = "passed"

        # Normalize method name (strip test_ prefix)
        method = name
        if method.startswith("test_"):
            method = method[5:]
        norm = normalize(method)

        results.setdefault(feature_stem, {})[norm] = status

    return results


# ---------------------------------------------------------------------------
# Matching & color computation
# ---------------------------------------------------------------------------


def match_scenario(
    scenario_norm: str,
    test_results: dict[str, str],
) -> str | None:
    """Find the test result status matching a normalized scenario name.

    Tries exact match first, then prefix / word-overlap heuristics.
    Returns status string or ``None`` if no test found.
    """
    # Exact match
    if scenario_norm in test_results:
        return test_results[scenario_norm]

    # Prefix match (scenario starts with test name or vice versa)
    for test_norm, status in test_results.items():
        if scenario_norm.startswith(test_norm) or test_norm.startswith(scenario_norm):
            return status

    # Word-overlap heuristic: ≥60 % of scenario words appear in test name
    scenario_words = set(scenario_norm.split())
    threshold = max(3, int(len(scenario_words) * 0.6))
    for test_norm, status in test_results.items():
        test_words = set(test_norm.split())
        if len(scenario_words & test_words) >= threshold:
            return status

    return None


def compute_colors(
    features: dict[str, list[str]],
    results: dict[str, dict[str, str]],
) -> dict[tuple[str, int], str]:
    """Map ``(feature_stem, scenario_1based_idx)`` → hex color."""
    colors: dict[tuple[str, int], str] = {}
    for stem, scenarios in features.items():
        feat_results = results.get(stem, {})
        for i, scenario_name in enumerate(scenarios, 1):
            status = match_scenario(normalize(scenario_name), feat_results)
            if status is None:
                color = RED
            elif status == "passed":
                color = BLUE
            else:
                color = GREEN
            colors[(stem, i)] = color
    return colors


# ---------------------------------------------------------------------------
# D2 file update
# ---------------------------------------------------------------------------


def update_d2(
    d2_path: Path,
    features_dir: Path,
    colors: dict[tuple[str, int], str],
) -> None:
    """Append (or replace) color-override section at end of the D2 file."""
    content = d2_path.read_text()

    # Strip existing color section
    if MARKER in content:
        content = content[: content.index(MARKER)].rstrip() + "\n"

    lines = [MARKER]
    for (stem, idx), color in sorted(colors.items()):
        tier_var = get_feature_tier(features_dir, stem)
        if tier_var is None:
            continue
        node = f"{tier_var}.{d2_id(stem)}.s{idx}"
        lines.append(f'{node}.style.fill: "{color}"')

    lines.append("")  # trailing newline
    d2_path.write_text(content + "\n".join(lines))


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def run_once(root: Path) -> float:
    """Run a single update cycle.  Returns the mtime of the XML consumed."""
    features_dir = root / "tests" / "features"
    d2_path = root / "docs" / "architecture-diagrams" / "testing-pyramid.d2"
    xml_path = root / ".test-results.xml"

    features = parse_features(features_dir)
    results = parse_junit_xml(xml_path)
    colors = compute_colors(features, results)
    update_d2(d2_path, features_dir, colors)

    total = len(colors)
    n_blue = sum(1 for c in colors.values() if c == BLUE)
    n_green = sum(1 for c in colors.values() if c == GREEN)
    n_red = sum(1 for c in colors.values() if c == RED)
    print(
        f"  updated {d2_path.name}: {total} scenarios "
        f"({n_blue} passing, {n_green} failing, {n_red} not implemented)"
    )

    try:
        return xml_path.stat().st_mtime
    except FileNotFoundError:
        return 0.0


def watch(root: Path) -> None:
    """Poll .test-results.xml and re-apply colors on change."""
    xml_path = root / ".test-results.xml"
    d2_path = root / "docs" / "architecture-diagrams" / "testing-pyramid.d2"

    last_xml_mtime = 0.0
    last_d2_mtime = 0.0

    print(f"  watching {xml_path.name} for changes (Ctrl+C to stop) ...")

    while True:
        changed = False

        # Check XML changes (new test results from pytest-watcher)
        try:
            xml_mt = xml_path.stat().st_mtime
        except FileNotFoundError:
            xml_mt = 0.0
        if xml_mt != last_xml_mtime and xml_mt > 0:
            changed = True
            last_xml_mtime = xml_mt

        # Check D2 changes (pyramid-watcher may have regenerated)
        try:
            d2_mt = d2_path.stat().st_mtime
        except FileNotFoundError:
            d2_mt = 0.0
        if d2_mt != last_d2_mtime:
            # Only re-apply if our marker section was wiped
            if d2_mt > 0 and MARKER not in d2_path.read_text():
                changed = True
            last_d2_mtime = d2_mt

        if changed:
            last_xml_mtime = run_once(root)
            # Update d2 mtime to our own write so we don't re-trigger
            try:
                last_d2_mtime = d2_path.stat().st_mtime
            except FileNotFoundError:
                pass

        time.sleep(1)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


def main() -> None:
    root = find_repo_root()
    run_once(root)
    if "--watch" in sys.argv:
        watch(root)


if __name__ == "__main__":
    main()
